import ingreso from "../icons/subjects/ingreso--image.jpg";
import biofisica from "../icons/subjects/fisica1--image.gif";

import algebra1 from "../icons/subjects/algebra1--image.png";
import algebra2 from "../icons/subjects/algebra2--image.jpeg";

import analisis1 from "../icons/subjects/analisis1--image.gif";
import analisis2 from "../icons/subjects/analisis2--image.jpg";

import fisica1 from "../icons/subjects/fisica1--image.gif";
import fisica2 from "../icons/subjects/fisica2--image.png";

import estabilidad1 from "../icons/subjects/estabilidad1--image.png";
import estabilidad2 from "../icons/subjects/estabilidad2--image.png";

export const subjectList = [
  {
    id: 0,
    countClasses: 10,
    image: ingreso,
    description: "Ingreso UTN",
    details: [
      { id: 0, topic: "Campo Eléctrico" },
      { id: 1, topic: "Potencial Eléctrico" },
      { id: 2, topic: "Capacit/ Dieléctricos" },
      { id: 3, topic: "Corriente Continua" },
      { id: 4, topic: "Campo Magnético" },
      { id: 5, topic: "Flujo/ Ley Faraday" },
      { id: 6, topic: "Inductancia" },
      { id: 7, topic: "Corriente Alterna" },
      { id: 8, topic: "Transf. De Calor" },
      { id: 9, topic: "Termodinámica" },
    ],
  },
  {
    id: 1,
    countClasses: 10,
    image: biofisica,
    description: "Biofísca CBC",
    details: [
      { id: 0, topic: "Campo Eléctrico" },
      { id: 1, topic: "Potencial Eléctrico" },
      { id: 2, topic: "Capacit/ Dieléctricos" },
      { id: 3, topic: "Corriente Continua" },
      { id: 4, topic: "Campo Magnético" },
      { id: 5, topic: "Flujo/ Ley Faraday" },
      { id: 6, topic: "Inductancia" },
      { id: 7, topic: "Corriente Alterna" },
      { id: 8, topic: "Transf. De Calor" },
      { id: 9, topic: "Termodinámica" },
    ],
  },
  {
    id: 2,
    countClasses: 10,
    image: algebra1,
    description: "Algebra 1",
    details: [
      { id: 0, topic: "Campo Eléctrico" },
      { id: 1, topic: "Potencial Eléctrico" },
      { id: 2, topic: "Capacit/ Dieléctricos" },
      { id: 3, topic: "Corriente Continua" },
      { id: 4, topic: "Campo Magnético" },
      { id: 5, topic: "Flujo/ Ley Faraday" },
      { id: 6, topic: "Inductancia" },
      { id: 7, topic: "Corriente Alterna" },
      { id: 8, topic: "Transf. De Calor" },
      { id: 9, topic: "Termodinámica" },
    ],
  },
  {
    id: 3,
    countClasses: 10,
    image: algebra2,
    description: "Algebra 2",
    details: [
      { id: 0, topic: "Campo Eléctrico" },
      { id: 1, topic: "Potencial Eléctrico" },
      { id: 2, topic: "Capacit/ Dieléctricos" },
      { id: 3, topic: "Corriente Continua" },
      { id: 4, topic: "Campo Magnético" },
      { id: 5, topic: "Flujo/ Ley Faraday" },
      { id: 6, topic: "Inductancia" },
      { id: 7, topic: "Corriente Alterna" },
      { id: 8, topic: "Transf. De Calor" },
      { id: 9, topic: "Termodinámica" },
    ],
  },
  {
    id: 4,
    countClasses: 10,
    image: analisis1,
    description: "Análisis 1",
    details: [
      { id: 0, topic: "Campo Eléctrico" },
      { id: 1, topic: "Potencial Eléctrico" },
      { id: 2, topic: "Capacit/ Dieléctricos" },
      { id: 3, topic: "Corriente Continua" },
      { id: 4, topic: "Campo Magnético" },
      { id: 5, topic: "Flujo/ Ley Faraday" },
      { id: 6, topic: "Inductancia" },
      { id: 7, topic: "Corriente Alterna" },
      { id: 8, topic: "Transf. De Calor" },
      { id: 9, topic: "Termodinámica" },
    ],
  },
  {
    id: 5,
    countClasses: 10,
    image: analisis2,
    description: "Análisis 2",
    details: [
      { id: 0, topic: "Campo Eléctrico" },
      { id: 1, topic: "Potencial Eléctrico" },
      { id: 2, topic: "Capacit/ Dieléctricos" },
      { id: 3, topic: "Corriente Continua" },
      { id: 4, topic: "Campo Magnético" },
      { id: 5, topic: "Flujo/ Ley Faraday" },
      { id: 6, topic: "Inductancia" },
      { id: 7, topic: "Corriente Alterna" },
      { id: 8, topic: "Transf. De Calor" },
      { id: 9, topic: "Termodinámica" },
    ],
  },
  {
    id: 6,
    countClasses: 10,
    image: fisica1,
    description: "Física 1",
    details: [
      { id: 0, topic: "Campo Eléctrico" },
      { id: 1, topic: "Potencial Eléctrico" },
      { id: 2, topic: "Capacit/ Dieléctricos" },
      { id: 3, topic: "Corriente Continua" },
      { id: 4, topic: "Campo Magnético" },
      { id: 5, topic: "Flujo/ Ley Faraday" },
      { id: 6, topic: "Inductancia" },
      { id: 7, topic: "Corriente Alterna" },
      { id: 8, topic: "Transf. De Calor" },
      { id: 9, topic: "Termodinámica" },
    ],
  },
  {
    id: 7,
    countClasses: 10,
    image: fisica2,
    description: "Física 2",
    details: [
      { id: 0, topic: "Campo Eléctrico" },
      { id: 1, topic: "Potencial Eléctrico" },
      { id: 2, topic: "Capacit/ Dieléctricos" },
      { id: 3, topic: "Corriente Continua" },
      { id: 4, topic: "Campo Magnético" },
      { id: 5, topic: "Flujo/ Ley Faraday" },
      { id: 6, topic: "Inductancia" },
      { id: 7, topic: "Corriente Alterna" },
      { id: 8, topic: "Transf. De Calor" },
      { id: 9, topic: "Termodinámica" },
    ],
  },
  {
    id: 8,
    countClasses: 10,
    image: estabilidad1,
    description: "Estabilidad 1",
    details: [
      { id: 0, topic: "Campo Eléctrico" },
      { id: 1, topic: "Potencial Eléctrico" },
      { id: 2, topic: "Capacit/ Dieléctricos" },
      { id: 3, topic: "Corriente Continua" },
      { id: 4, topic: "Campo Magnético" },
      { id: 5, topic: "Flujo/ Ley Faraday" },
      { id: 6, topic: "Inductancia" },
      { id: 7, topic: "Corriente Alterna" },
      { id: 8, topic: "Transf. De Calor" },
      { id: 9, topic: "Termodinámica" },
    ],
  },
  {
    id: 9,
    countClasses: 10,
    image: estabilidad2,
    description: "Estabilidad 2",
    details: [
      { id: 0, topic: "Campo Eléctrico" },
      { id: 1, topic: "Potencial Eléctrico" },
      { id: 2, topic: "Capacit/ Dieléctricos" },
      { id: 3, topic: "Corriente Continua" },
      { id: 4, topic: "Campo Magnético" },
      { id: 5, topic: "Flujo/ Ley Faraday" },
      { id: 6, topic: "Inductancia" },
      { id: 7, topic: "Corriente Alterna" },
      { id: 8, topic: "Transf. De Calor" },
      { id: 9, topic: "Termodinámica" },
    ],
  },
];
