import ingreso from "../icons/subjects/ingreso--image.jpg";
import biofisica from "../icons/subjects/fisica1--image.gif";

import algebra1 from "../icons/subjects/algebra1--image.png";
import algebra2 from "../icons/subjects/algebra2--image.jpeg";

import analisis1 from "../icons/subjects/analisis1--image.gif";
import analisis2 from "../icons/subjects/analisis2--image.jpg";

import fisica1 from "../icons/subjects/fisica1--image.gif";
import fisica2 from "../icons/subjects/fisica2--image.png";

import estabilidad1 from "../icons/subjects/estabilidad1--image.png";
import estabilidad2 from "../icons/subjects/estabilidad2--image.png";

export const subjectList = [
  {
    id: 0,
    countClasses: 10,
    image: ingreso,
    description: "Ingreso UTN",
    details: [
      { id: 0, topic: "Funciones 1" },
      { id: 1, topic: "Funciones 2" },
      { id: 2, topic: "Polinomios" },
      { id: 3, topic: "Algebra" },
      { id: 4, topic: "Trigonometria" },
      { id: 5, topic: "Geometría" },
      { id: 6, topic: "Cinemática 1" },
      { id: 7, topic: "Cinemática 2" },
      { id: 8, topic: "Estática 1" },
      { id: 9, topic: "Estática 2" },
    ],
  },
  {
    id: 1,
    countClasses: 10,
    image: biofisica,
    description: "Biofísca CBC",
    details: [
      { id: 0, topic: "Campo Eléctrico" },
      { id: 1, topic: "Potencial Eléctrico" },
      { id: 2, topic: "Capacit/ Dieléctricos" },
      { id: 3, topic: "Corriente Continua" },
      { id: 4, topic: "Campo Magnético" },
      { id: 5, topic: "Flujo/ Ley Faraday" },
      { id: 6, topic: "Inductancia" },
      { id: 7, topic: "Corriente Alterna" },
      { id: 8, topic: "Transf. De Calor" },
      { id: 9, topic: "Termodinámica" },
    ],
  },
  {
    id: 2,
    countClasses: 10,
    image: algebra1,
    description: "Algebra 1",
    details: [
      { id: 0, topic: "Rectas/ Planos R2" },
      { id: 1, topic: "Rectas/ Planos R3" },
      { id: 2, topic: "Matrices" },
      { id: 3, topic: "Determinantes" },
      { id: 4, topic: "Sistemas Ecuaciones" },
      { id: 5, topic: "Espacios Vectoriales 1" },
      { id: 6, topic: "Espacios Vectoriales 2" },
      { id: 7, topic: "Corriente Alterna" },
      { id: 8, topic: "Transf. De Calor" },
      { id: 9, topic: "Termodinámica" },
    ],
  },
  {
    id: 3,
    countClasses: 10,
    image: algebra2,
    description: "Algebra 2",
    details: [
      { id: 0, topic: "Transf. Lineales 1" },
      { id: 1, topic: "Transf. Lineales 2" },
      { id: 2, topic: "Autovalores" },
      { id: 3, topic: "Autovectores" },
      { id: 4, topic: "Cónicas 1" },
      { id: 5, topic: "Cónicas 2" },
      { id: 6, topic: "Superficies 1" },
      { id: 7, topic: "Superficies 2" },
      { id: 8, topic: "Rototraslacion" },
      { id: 9, topic: "Rototraslacion" },
    ],
  },
  {
    id: 4,
    countClasses: 10,
    image: analisis1,
    description: "Análisis 1",
    details: [
      { id: 0, topic: "Funciones" },
      { id: 1, topic: "Límites 1" },
      { id: 2, topic: "Continuidad" },
      { id: 3, topic: "Derivadas 1" },
      { id: 4, topic: "Derivadas 2" },
      { id: 5, topic: "Polinomios" },
      { id: 6, topic: "Integrales 1" },
      { id: 7, topic: "Integrales 2" },
      { id: 8, topic: "Series" },
      { id: 9, topic: "Sucesiones" },
    ],
  },
  {
    id: 5,
    countClasses: 10,
    image: analisis2,
    description: "Análisis 2",
    details: [
      { id: 0, topic: "Ecuac. Diferenciales 1" },
      { id: 1, topic: "Limites Dobles" },
      { id: 2, topic: "Continuidad/ Derivabilidad" },
      { id: 3, topic: "Diferenciabilidad" },
      { id: 4, topic: "Derivada Compuesta" },
      { id: 5, topic: "Areas" },
      { id: 6, topic: "Circularion" },
      { id: 7, topic: "Flujo" },
      { id: 8, topic: "Volumen/ Masa" },
      { id: 9, topic: "Ecuac. Diferenciales 2" },
    ],
  },
  {
    id: 6,
    countClasses: 10,
    image: fisica1,
    description: "Física 1",
    details: [
      { id: 0, topic: "Optica Geometrica" },
      { id: 1, topic: "Cinemática" },
      { id: 2, topic: "Dinámica" },
      { id: 3, topic: "Energía Mecánica 1" },
      { id: 4, topic: "Energía Mecánica 2" },
      { id: 5, topic: "Momentos Lineales" },
      { id: 6, topic: "Cuerpo Rígido 1" },
      { id: 7, topic: "Cuerpo Rígido 2" },
      { id: 8, topic: "Cuerpo Rígido 3" },
      { id: 9, topic: "Fluidos" },
    ],
  },
  {
    id: 7,
    countClasses: 10,
    image: fisica2,
    description: "Física 2",
    details: [
      { id: 0, topic: "Transf. De Calor" },
      { id: 1, topic: "Termodinámica" },
      { id: 2, topic: "Electrostática 1" },
      { id: 3, topic: "Electrostática 2" },
      { id: 4, topic: "Capacitores* Dieléctricos" },
      { id: 5, topic: "Corriente Continua" },
      { id: 6, topic: "Magnetismo 1" },
      { id: 7, topic: "Magnetismo 2" },
      { id: 8, topic: "Magnetismo 3" },
      { id: 9, topic: "Corriente Alterna" },
    ],
  },
  {
    id: 8,
    countClasses: 10,
    image: estabilidad1,
    description: "Estabilidad 1",
    details: [
      { id: 0, topic: "Tema 0" },
      { id: 1, topic: "Tema 1" },
      { id: 2, topic: "Tema 2" },
      { id: 3, topic: "Tema 3" },
      { id: 4, topic: "Tema 4" },
      { id: 5, topic: "Tema 5" },
      { id: 6, topic: "Tema 6" },
      { id: 7, topic: "Tema 7" },
      { id: 8, topic: "Tema 8" },
      { id: 9, topic: "Tema 9" },
    ],
  },
  {
    id: 9,
    countClasses: 10,
    image: estabilidad2,
    description: "Estabilidad 2",
    details: [
      { id: 0, topic: "Tema 0" },
      { id: 1, topic: "Tema 1" },
      { id: 2, topic: "Tema 2" },
      { id: 3, topic: "Tema 3" },
      { id: 4, topic: "Tema 4" },
      { id: 5, topic: "Tema 5" },
      { id: 6, topic: "Tema 6" },
      { id: 7, topic: "Tema 7" },
      { id: 8, topic: "Tema 8" },
      { id: 9, topic: "Tema 9" },
    ],
  },
];
